language: perl

install:
  - cpanm -n FFI::Raw
  - cpanm -n FFI::Util
  #- cpanm -n https://dist.wdlabs.com/ffi/FFI-Sweet-0.001.tar.gz
  - cpanm -n Inline::C
  - cpanm -n File::chdir
  - cpanm -n FFI::Platypus
  - cpanm -n Archive::Libarchive::FFI
  #- cpanm  -n Archive::Libarchive::XS
  - cpanm -n IPC::System::Simple
  - cpanm -n Test2 Test2::Suite

perl:
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - perl Build.PL
  - ./Build 
  - ./Build test verbose=1
  - perl -Mblib bin/ffi-performance-benchmark
  #- perl -Mblib bin/archive-performance-benchmak


