---
abstract: 'Measure FFI performance'
author:
  - 'Graham Ollis <plicease@wdlabs.com>'
build_requires:
  ExtUtils::CBuilder: '0'
configure_requires:
  File::chdir: '0'
  Module::Build: '0.42'
  autodie: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Performance
provides:
  FFI::Performance:
    file: lib/FFI/Performance.pm
    version: '0.01'
  FFI::Performance::Inline:
    file: lib/FFI/Performance/Inline.pm
  FFI::Performance::Platypus:
    file: lib/FFI/Performance/Platypus.pm
  FFI::Performance::PlatypusSl:
    file: lib/FFI/Performance/PlatypusSl.pm
  FFI::Performance::Raw:
    file: lib/FFI/Performance/Raw.pm
  FFI::Performance::Sweet:
    file: lib/FFI/Performance/Sweet.pm
  FFI::Performance::SweetLite:
    file: lib/FFI/Performance/SweetLite.pm
  FFI::Performance::SweetLite2:
    file: lib/FFI/Performance/SweetLite2.pm
  FFI::Performance::XS:
    file: lib/FFI/Performance/XS.pm
    version: '0.01'
requires:
  Archive::Libarchive::FFI: '0'
  FFI::Platypus: '0.09'
  FFI::Raw: '0'
  FFI::Sweet: '0'
  FFI::Util: '0'
  File::chdir: '0'
  Inline::C: '0.56'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
